# DHCP/DNS only on the virtual AP interface (uap0)
interface=uap0
domain-needed
bogus-priv
server=8.8.8.8
server=8.8.4.4
dhcp-range=192.168.4.10,192.168.4.100,255.255.255.0,24h
dhcp-option=3,192.168.4.1
dhcp-option=6,192.168.4.1
dhcp-leasefile=/var/lib/misc/dnsmasq.leases
bind-interfaces
